language: ruby
branches:
  only:
  - source
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy
env:
  global:
    secure: IWrhzk11r1x02CaVmyi04ncv0BpLpfEAmNhdJGDydOWGE/j4C3R/1o/VQkw152QcDROudcbscxFBNaB6ZSAm49957r8yQhG1sobP5Nwc/TGNLOdrIDXhW8fGOI0kfYuz+X9jkQXrXJi5g0UlOZ8NoZCdj9VP7Q4cA9bRQAHjPQXYuATDJMegFhRsKJVBWD7x11aCgO40I1DYPNWLi1Sn7HqrPyTfwxyjI49mCZ4HN5YxSwNPYrEui3d7+UyjRLpGN13/45hdXWvDnE4KPMQej3MsY9kCEqfa880yCB57UOypBPKKmmfDIRyfQwrr/Io6r/A6kc50tDq52jyioubyhcxkN9Y5ZRjFrlwBJJF1m4Fg3ELD/KZLxKEV2BRQaKp1ORMaTbj1Dp8eHG0BdTpLwypxOUBXSK1Hs49jvCyPnaHQFkpBy9LaVlXzxLb/vCvGydlUKIpoT8rAl76+HIE8691f0i9z/Lgkt/hDrhdszQGTxTQldh2mprl/jDzab4qpHZdGOwZCQ86cb8Y/nCp5tOFu7xtkXYEd8mB2CGiqMtxCGTI4gEIuLhFCop9BFwtbUjqS2+528RZne/dIsoSDYhagvm08w2JdAxAbZCA+2tzl+4D3jxfh7bIiSZhVpAsSOkHewb+4G5mmfI9pHn9dUs4M7v/8ZYUa6gHvTt+WQC0=
