language: ruby
rvm:
- 2.3.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
  - secure: aH+h26+kvwyyuwVWwwNykZXLaCu1PQ/E4Bw0ccsWXhv+i9qxSqYU5szrxpziXe6g54t6L+1GWx11PcVdylPs0XtspLBvqZa3lWQj4hpJjsXhUrvnV3Wdp8X5ime+3vXmiL7vrhlLBrhHFgQtvdDh8CEZOlBISJY4S5unmEjFKt0UfXjQFyTtmKXK0yGCk0gKOwBCAsZNHocbtuAlWRRyd/N94lX3RtfbWZlPYaABLc/+AqI7CXMNzwX2aksTy+KDEMwUq5Noc9sArIbSEJC1pCDcYmmiCMXU89x9JzDAgzCOI6l3zXkOwcy6hYq8xDhd0t57JJAkqAJdIRcyjVeboKc34MsPFqaosA4XDBTt8azccvhJn+knGy/cdlhiv+kjWic8WQs1EEyys7I2OB2EXUicjh5u6Vh8zqxppjY6P8FPhUg9ZFMmITL1G4InBNO/lPka0N5yaIadZg1urUkXuGl5DT1X9OrrKj9TAhbm5X93h2VzveUf/r5zOaJSocgPgHcfltyVqhc4mA9PiCa79lFZSAjXtoe3n9FR194uBMzf27YHsvVrw3iRpKXZWZpLGKBVpQqF4nLK5j+D2M+WOPUYKIgLc32ascstqbIInWcto+qjr0lDqkNUmuPmDw6q7rickPDCdIK8l8POwX8VPEwW8Om7B4aUytYAYjbfdOU=
