title: Yao Ding
email: yaodingyd@gmail.com
description: "Yao's blog on everything about web technologies'"
baseurl: ""
tag_page: "/blog/tags"
url: "https://yaodingyd.github.io" 
github_username:  yaodingyd

permalink: /blog/:title/
paginate: 8

markdown: kramdown
theme: minima

include: ["_pages"]
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
