title: Yao Ding
email: yaodingyd@gmail.com
description: "Yao's blog on everything about web technologies'"
baseurl: ""
url: "https://yaodingyd.github.io" 
github_username:  yaodingyd

plugins:
  - jekyll-paginate
  - jekyll-archives

permalink: /blog/:title/
paginate: 5
paginate_path: /page-:num/

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    tag: '/tag/'

markdown: kramdown
highlighter: rouge

include: ["_pages"]
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - package-lock.json
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile
  - .sass-cache
  - _js
  - public

# GitHub
username:             yaodingyd
repo:                 yaodingyd.github.io
branch:               source

# Jekyll source / destination
source:               .
destination:          _site
